export const copy = {
  brand: 'Signal',
  brandDescriptor: 'security / engineering / AI',
  skip: 'skip to content',
  home: 'home',
  header: {
    cta: 'get in touch',
    menu: 'open navigation',
    close: 'close navigation',
    navigation: 'main navigation',
    featured: 'Featured projects',
    domains: 'By domain',
    artefacts: 'Artefacts',
    all: 'all work',
    search: 'search the site',
    keyboard: 'Ctrl K',
  },
  hero: {
    label: 'A portfolio by Joehan Fernando',
    work: 'see the work',
    resume: 'download résumé',
    cue: 'scroll to explore',
    field: 'signal field',
    mode: 'interactive study',
    static: 'static study',
    inspect: 'move to inspect',
    discipline: 'Cybersecurity & AI engineering',
    coordinate: '01 / 04',
    caption: 'From alert analysis to agentic workflows.',
    reading: 'signal / noise',
  },
  work: {
    title: 'Evidence in the work.',
    intro:
      'Ordered by relevance to security and applied engineering. Four projects, from analyst decision support to automated workflows.',
    label: 'selected work',
    all: 'explore all work',
    view: 'view case study',
    developed: 'developed',
    progress: 'in progress',
    concept: 'architecture study',
    problem: 'The problem',
    approach: 'The approach',
    result: 'The result',
    stack: 'Built with',
    related: 'Next project',
    previous: 'Previous project',
    overview: 'all projects',
    indexTitle: 'Systems, built to be useful.',
    indexIntro: 'Security operations, automation, and AI. Explore the work by domain.',
    filter: 'filter by domain',
    allFilter: 'all',
    caseNote:
      'Project summary drawn from the résumé. Diagrams illustrate the described architecture; they are not product screenshots.',
  },
  credibility: {
    title: 'Tools behind the work',
    pause: 'pause moving text',
    play: 'resume moving text',
  },
  method: {
    title: 'How the pieces connect.',
    intro: 'A working approach, illustrated by the SOC triage and subscription projects.',
    label: 'method',
    link: 'see it in the work',
    progress: 'method progress',
  },
  manifesto: 'Understand the system. Build something useful.',
  skills: {
    title: 'A connected skill set.',
    intro: 'Across security, software, and the systems between them.',
    label: 'capabilities',
    count: 'listed skills',
  },
  timeline: {
    title: 'Learning, applied.',
    label: 'experience & education',
    undated: 'date not provided',
    education: 'education',
    full: 'read the full résumé',
  },
  search: {
    title: 'What are you looking for?',
    intro: 'Follow a skill to the work behind it.',
    placeholder: 'type a skill, a tool, or a threat.',
    label: 'search work and skills',
    empty: 'Start with a tool, a domain, or a project.',
    none: 'Nothing yet. Explore these related capabilities and projects.',
    matches: 'matches',
    presets: ['SOC', 'automation', 'Python', 'AI agents', 'OWASP'],
    skills: 'capabilities',
    projects: 'projects',
    clear: 'clear search',
  },
  contact: {
    title: 'Let’s make it useful.',
    intro: 'For a role, a project, or a technical conversation.',
    email: 'email',
    phone: 'phone',
    copy: 'copy email address',
    copied: 'email copied',
    copyFailed: 'Copy unavailable. Use the email link below.',
    emailLink: 'open email',
    name: 'name',
    emailField: 'email address',
    message: 'message',
    namePlaceholder: 'Your name',
    emailPlaceholder: 'you@example.com',
    messagePlaceholder: 'What would you like to work on?',
    send: 'send message',
    sending: 'sending message',
    success: 'Sent. Your message has been delivered for Joehan to review.',
    unavailable: 'Message delivery is not configured yet. Please use the email link.',
    error: 'Your message could not be sent. Try again or use the email link.',
    limited: 'Too many attempts. Please try again in an hour or use the email link.',
    invalid: 'Check the highlighted fields and try again.',
    website: 'leave this field empty',
    notice: 'Your name, email, and message are used to respond to your enquiry.',
    shortName: 'Enter at least 2 characters.',
    invalidEmail: 'Enter a valid email address.',
    shortMessage: 'Enter at least 10 characters.',
    longName: 'Keep your name under 100 characters.',
    longEmail: 'Keep your email under 254 characters.',
    longMessage: 'Keep your message under 5,000 characters.',
  },
  footer: {
    title: 'Good work starts with a conversation.',
    explore: 'Explore',
    connect: 'Connect',
    resources: 'Resources',
    copyright: 'Joehan Antony Fernando J',
    stamp: 'built with Next.js',
    top: 'back to top',
    motionOn: 'motion on',
    motionOff: 'motion off',
    motionEnabled: 'Motion enabled.',
    motionDisabled: 'Reduced motion enabled.',
    llms: 'llms.txt',
    sitemap: 'sitemap',
  },
  about: {
    title: 'Curiosity, put to work.',
    opening:
      'I’m a computer science student working at the intersection of security operations and AI. I learn by building, experimenting, and turning a problem into something practical.',
    body: 'SOC experience shapes my interest in security. Java and Selenium training broadened my work into QA automation, while agentic AI opened another way to prototype practical solutions.',
    interests: 'Away from the terminal',
    interestItems: [
      'Football',
      'Red teaming',
      'Game console technology',
      'Cryptocurrency & blockchain',
    ],
    location: 'based in',
    focus: 'Current areas of learning',
    focusText: 'Penetration testing and AI security.',
  },
  resume: {
    title: 'The record, in plain text.',
    summary: 'Personal summary',
    experience: 'Internship experience',
    education: 'Education',
    skills: 'Skills',
    projects: 'Projects',
    interests: 'Hobbies and interests',
    download: 'download original PDF',
    note: 'HTML transcription of the supplied résumé. Unprovided dates and profile links are omitted.',
  },
  palette: {
    title: 'Find your signal.',
    placeholder: 'search projects, skills, or actions',
    close: 'close search',
    recent: 'recent',
    actions: 'actions',
    pages: 'pages',
    noResults: 'No matches. Try a project, tool, or page name.',
    hint: 'navigate',
    select: 'open',
    escape: 'close',
    toggle: 'toggle motion',
    copy: 'copy email',
    download: 'download résumé',
    searchLabel: 'site command search',
  },
  notFound: {
    title: 'Path not found.',
    code: '404',
    status: 'lookup / failed',
    body: 'This route doesn’t exist. There’s still a signal to follow.',
    terminal: 'route terminal',
    placeholder: 'type help',
    intro: 'A small terminal. Type help to explore.',
    timeout: 'Terminal session ended. Use the navigation links to continue.',
    unknown: 'Unknown command. Type help.',
    help: 'help / whoami / ls / work / contact',
    commands: ['help', 'whoami', 'ls', 'work', 'contact'],
    prompt: 'signal >',
    run: 'run command',
    reset: 'restart terminal',
    skip: 'skip terminal',
  },
  preloader: { label: 'initialising signal', percent: '%', ready: 'ready' },
  hud: { label: 'page progress' },
  cursor: { view: 'view', copy: 'copy', drag: 'drag' },
  seo: {
    description:
      'Joehan Antony Fernando J — computer science, SOC experience, security projects, and agentic AI development.',
    ogLabel: 'Security. Engineering. AI.',
    breadcrumb: 'Breadcrumbs',
  },
};
